### ISSUE TITLE
Accept self signed TLS/SSL certs in sentry self hosted.

### ISSUE THREAD

**Issue by MuhmdHsn313** [getsentry/sentry-dart#1332]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
```
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
    • Flutter version 3.7.7 on channel stable at C:\src\flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = ssh://git@github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (7 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\muhammad.hasan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.76.1)
    • VS Code at C:\Users\muhammad.hasan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]     
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 111.0.5563.64
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 111.0.1661.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
The version of the SDK (See pubspec.lock):
**3.7.7**

---
I have the following issue:

I deployed the self-host version of a sentry with a self-signed TLS/SSL certificate, when I set the DSN and start the flutter application the OkHttp reject the certificate and throw an error, after that there is no issue sent to the sentry self-host. I try to use a custom HTTP client and accept all certs and set it as a sentry HTTP client but there is no thing happened.

**Steps to reproduce:**
- Deploy self-hosted sentry
- Create a new flutter project in sentry
- Set the DSN of the flutter project into the flutter code
- Define custom HTTP client
- Set client to sentry
```dart
await SentryFlutter.init(
    (options) {
      options.dsn = sentryDsn;
      options.tracesSampleRate = 1.0;
      options.enableNativeCrashHandling = true;
      options.httpClient = SentryHttpClient(
        client: CustomClient(),
        captureFailedRequests: true,
      );
      options.environment = env;
      options.debug = true;
    },
    appRunner: () => MyApp(),
);
```

**Actual result:**
```
E/Sentry  ( 3181): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:677)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
E/Sentry  ( 3181): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/Sentry  ( 3181): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/Sentry  ( 3181): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/Sentry  ( 3181): 	... 28 more
E/Sentry  ( 3181): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/Sentry  ( 3181): 	... 42 more
D/Sentry  ( 3181): Marking envelope submission result: false
W/Sentry  ( 3181): Envelope had a failed capture at item 1. No more items will be sent.
D/Sentry  ( 3181): File '/data/user/0/com.alqaseh.consumer.stage/cache/sentry/a484308fbe2ac27a71694e3141cd9fcbf356fa1c/outbox/3b11c2a2-660d-4d80-8682-632d679e26d4' is done.
D/Sentry  ( 3181): Finished processing cached files from /data/user/0/com.alqaseh.consumer.stage/cache/sentry/a484308fbe2ac27a71694e3141cd9fcbf356fa1c/outbox
```
**Expected result:**
- Connect to sentry and sent the issues.

**Comment by marandaneto** [comment]
You'll have to [manually init](https://docs.sentry.io/platforms/flutter/native-init/) the Native SDKs.
So you can pin/configure the Android options with your own certificate/hostname/ssl factory.
[Here are the options](https://github.com/getsentry/sentry-java/blob/af5051f07717cf29b95e602cdc9987a74f6fc19b/sentry/src/main/java/io/sentry/SentryOptions.java#L269-L273).
