### ISSUE TITLE
Sentry gives wrong (and misleading :/ ) stack traces

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#1429]
Hi thanks for the error-reporting solution! However, it gives wrong and misleading stack traces :(

### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

<details>

```
(base) ➜  python_mono git:(feat/8716) flutter doctor -v
[✓] Flutter (Channel stable, 3.7.7, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.7 on channel stable at /Users/tom/fvm/versions/3.7.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/tom/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8617.56/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
...

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### Version

https://github.com/fzyzcjy/sentry-dart

### Steps to Reproduce

The stack trace given by sentry looks quite weird and seems wrong compared to the ground truth.

This is the stack trace reported by sentry:

![image](https://github.com/getsentry/sentry-dart/assets/5236035/858b3f31-df55-4e77-b092-037e9ffc48ef)

(Btw I cannot paste a text version here since the raw stack trace errors as follows)

![image](https://github.com/getsentry/sentry-dart/assets/5236035/9f54b43f-c4f4-4290-9f80-17f1755e54c0)

This seems to be incorrect for two reasons:

#### Reason 1: It seems impossible for `ComponentElement._firstBuild(framework.dart:4950)` to directly call `RenderBox.size(box.dart:2031)`

I have checked its source code, there seems to be no such call. I even thought about code inlining, but there is still none (note: sentry knows inlined functions and display them well usually... So even if there is code inlining, this should not make functions disappear). 

#### Reason 2: I have attached another copy of `FlutterErrorDetails.stack` when `FlutterError.onError` is called

That one looks like:

```


FlutterError.onError raw stackTrace=*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** pid: 32734, tid: 457, name 1.ui os: android arch: arm comp: no sim: no build_id: 'f467c85f82223fe669d020a6221bc1cb' isolate_dso_base: c2318000, vm_dso_base: c2318000 isolate_instructions: c2890e00, vm_instructions: c288c000     #00 abs c2a5f0cf virt 007470cf _kDartIsolateSnapshotInstructions+0x1ce2cf     dart-lang/tools#1817 abs c2a5f743 virt 00747743 _kDartIsolateSnapshotInstructions+0x1ce943     dart-lang/stack_trace#2 abs c2b40aeb virt 00828aeb _kDartIsolateSnapshotInstructions+0x2afceb     dart-lang/tools#1818 abs c2b4018f virt 0082818f _kDartIsolateSnapshotInstructions+0x2af38f     dart-lang/tools#1819 abs c2e3fb1f virt 00b27b1f _kDartIsolateSnapshotInstructions+0x5aed1f     dart-lang/tools#1820 abs c304ed97 virt 00d36d97 _kDartIsolateSnapshotInstructions+0x7bdf97     dart-lang/tools#1821 abs c34c9947 virt 011b1947 _kDartIsolateSnapshotInstructions+0xc38b47     dart-lang/stack_trace#7 abs c304ebaf virt 00d36baf _kDartIsolateSnapshotInstructions+0x7bddaf     dart-lang/tools#1822 abs c304c27f virt 00d3427f _kDartIsolateSnapshotInstructions+0x7bb47f     dart-lang/tools#1823 abs c304cef7 virt 00d34ef7 _kDartIsolateSnapshotInstructions+0x7bc0f7     dart-lang/tools#1824 abs c304c97b virt 00d3497b _kDartIsolateSnapshotInstructions+0x7bbb7b     dart-lang/tools#1825 abs c34c9947 virt 011b1947 _kDartIsolateSnapshotInstructions+0xc38b47     dart-lang/stack_trace#12 abs c2db2087 virt 00a9a087 _kDartIsolateSnapshotInstructions+0x521287     dart-lang/stack_trace#13 abs c304edbb virt 00d36dbb _kDartIsolateSnapshotInstructions+0x7bdfbb     dart-lang/tools#1826 abs c34c9947 virt 011b1947 _kDartIsolateSnapshotInstructions+0xc38b47     dart-lang/stack_trace#15 abs c2db2087 virt 00a9a087 _kDartIsolateSnapshotInstructions+0x521287     dart-lang/tools#1827 abs c304edbb virt 00d36dbb _kDartIsolateSnapshotInstructions+0x7bdfbb     dart-lang/stack_trace#17 abs c304c27f virt 00d3427f _kDartIsolateSnapshotInstructions+0x7bb47f     dart-lang/stack_trace#18 abs c34c9947 virt 011b1947 _kDartIsolateSnapshotInstructions+0xc38b47     dart-lang/stack_trace#19 abs c2db2087 virt 00a9a087 
...
```

After de-obfuscation:

```
(base) ➜  bug flutter symbolize --debug-info /Users/tom/Main/yplusplus/frontend/yplusplus/build/split-debug-info/app.android-arm.symbols --input a.txt  
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 32734, tid: 457, name 1.ui
os: android arch: arm comp: no sim: no
build_id: 'f467c85f82223fe669d020a6221bc1cb'
isolate_dso_base: c2318000, vm_dso_base: c2318000
isolate_instructions: c2890e00, vm_instructions: c288c000
#0      RenderBox.size (package:flutter/src/rendering/box.dart:2031:17)
dart-lang/tools#1817      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:3045:24)
dart-lang/stack_trace#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2968:24)
dart-lang/tools#1818      MyEditableTextState._updateSizeAndTransform (package:third_party_flutter/src/my_flutter/my_text_field/my_editable_text.dart:3592:48)
dart-lang/tools#1819      MyEditableTextState._openInputConnection (package:third_party_flutter/src/my_flutter/my_text_field/my_editable_text.dart:2984:7)
dart-lang/tools#1820      MyEditableTextState.didUpdateWidget (package:third_party_flutter/src/my_flutter/my_text_field/my_editable_text.dart:2510:7)
dart-lang/tools#1821      StatefulElement.update (package:flutter/src/widgets/framework.dart:5142:55)
dart-lang/stack_trace#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
dart-lang/tools#1822      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
dart-lang/tools#1823      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
dart-lang/tools#1824     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
dart-lang/tools#1825     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
dart-lang/stack_trace#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
dart-lang/stack_trace#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
dart-lang/tools#1826     SlottedRenderObjectElement._updateChildren (package:flutter/src/widgets/slotted_render_object_widget.dart:270:33)
dart-lang/stack_trace#15     SlottedRenderObjectElement.update (package:flutter/src/widgets/slotted_render_object_widget.dart:231:5)
dart-lang/tools#1827     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
dart-lang/stack_trace#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
dart-lang/stack_trace#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
dart-lang/stack_trace#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
...
```

As you can see, the latter looks much more reasonable! (Indeed I created issue/PR for that Flutter framework bug later - https://github.com/flutter/flutter/issues/126312 / https://github.com/flutter/flutter/pull/126324 ). So this double-confirms that the sentry stack trace seems not very correct.

### Expected Result

correct stack trace

### Actual Result

incorrect stack trace

### Are you willing to submit a PR?

Yes

**Comment by marandaneto** [comment]
@fzyzcjy could it be that sometimes we get the current stack trace from `Stacktrace.current` if no stack trace is given?
It's strange because sentry only converts the dart stack trace into the sentry's trace, we don't do anything fancy besides that, so I'm not really sure if it's indeed a problem in the SDK.
I wonder if it could be related to https://github.com/dart-lang/tools/issues/1857 depending on how you chain the async calls.
Can you provide a minimal reproducible example where I can reproduce this easily?

**Comment by fzyzcjy** [comment]
@marandaneto I will try to make a minimal sample but cannot guarantee. This may not be the top in my priority list though, since I decide to attach (raw) stacktrace by myself instead of relying on Sentry's stack trace - trusting Sentry's reported stack trace wasted me several hours because it was wrong :( But anyway, sentry is a good and helpful package!

> could it be that sometimes we get the current stack trace from Stacktrace.current if no stack trace is given?
It's strange because sentry only converts the dart stack trace into the sentry's trace, we don't do anything fancy besides that, so I'm not really sure if it's indeed a problem in the SDK.

That's why I also feel weird.

Btw here is the initialization code, and how I attach the extra stack trace

```dart
    await SentryFlutter.init(
      _sentryHandler.configureOptions
    );


    final oldOnError = FlutterError.onError;
    FlutterError.onError = (details) {
      bindExtraToException(details.exception, 'FlutterError.onError raw stackTrace=${details.stack}'); // <---- NOTE
      oldOnError?.call(details);
    };

    await appRunner

**Comment by marandaneto** [comment]
@fzyzcjy thanks for the feedback, I will wait for the minimal sample.
We do capture the stack trace in the very same way. using `details.exception` and `details.stack`.

**Comment by marandaneto** [comment]
@fzyzcjy have you had the time to set up a minimal reproducible example or even share at least the way how you throw the exception? I'm still intrigued by this issue and I'd say it's a rather important one because stack traces are the best info for solving issues.
We use the very same `details.stack` so I don't see how this could be different, a repro would definitely help here.

https://github.com/getsentry/sentry-dart/blob/d883d62345e5c21066faf14885eea7afd75b89e1/dart/lib/src/sentry_exception_factory.dart#L19-L66
As you can see, we always use the given `stackTrace`, as long as `details.stack` isn't null nor empty.

**Comment by fzyzcjy** [comment]
@marandaneto Hi thanks for the attention. However, I am very busy recently and have no time to make a minimal reproducible sample. I also think this is very weird and should never happen.

**Comment by marandaneto** [comment]
@fzyzcjy closing it as non-reproducible but let me know if you have the time to create a minimal reproducible sample, so I can reopen the issue, thanks.
