### ISSUE TITLE
Upgrading Flutter and Sentry causes crash on Android at runtime

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#1704]
Flutter upgraded, and Sentry SDK upgraded together (to version `7.11`). And fails at runtime with:

```
D/Sentry  (23065): Class not available:androidx.compose.ui.node.Owner
D/Sentry  (23065): java.lang.ClassNotFoundException: androidx.compose.ui.node.Owner
D/Sentry  (23065):      at java.lang.Class.classForName(Native Method)
D/Sentry  (23065):      at java.lang.Class.forName(Class.java:536)
D/Sentry  (23065):      at java.lang.Class.forName(Class.java:467)
D/Sentry  (23065):      at io.sentry.android.core.LoadClass.loadClass(LoadClass.java:21)
D/Sentry  (23065):      at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:39)
D/Sentry  (23065):      at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:44)
D/Sentry  (23065):      at io.sentry.android.core.AndroidOptionsInitializer.initializeIntegrationsAndProcessors(AndroidOptionsInitializer.java:147)
D/Sentry  (23065):      at io.sentry.android.core.SentryAndroid.lambda$init$1(SentryAndroid.java:127)
D/Sentry  (23065):      at io.sentry.android.core.SentryAndroid$$ExternalSyntheticLambda0.configure(Unknown Source:8)
D/Sentry  (23065):      at io.sentry.Sentry.applyOptionsConfiguration(Sentry.java:176)
D/Sentry  (23065):      at io.sentry.Sentry.init(Sentry.java:146)
D/Sentry  (23065):      at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
D/Sentry  (23065):      at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
D/Sentry  (23065):      at io.sentry.flutter.SentryFlutterPlugin.initNativeSdk(SentryFlutterPlugin.kt:126)
D/Sentry  (23065):      at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.kt:57)
D/Sentry  (23065):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
D/Sentry  (23065):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
D/Sentry  (23065):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
D/Sentry  (23065):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
D/Sentry  (23065):      at android.os.Handler.handleCallback(Handler.java:958)
D/Sentry  (23065):      at android.os.Handler.dispatchMessage(Handler.java:99)
D/Sentry  (23065):      at android.os.Looper.loopOnce(Looper.java:205)
D/Sentry  (23065):      at android.os.Looper.loop(Looper.java:294)
D/Sentry  (23065):      at android.app.ActivityThread.main(ActivityThread.java:8176)
D/Sentry  (23065):      at java.lang.reflect.Method.invoke(Native Method)
D/Sentry  (23065):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
D/Sentry  (23065):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
D/Sentry  (23065): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.ui.node.Owner" on path: DexPathList

```

Originally posted on: https://stackoverflow.com/questions/77368189/didnt-find-class-androidx-compose-ui-node-owner-sentry

**Comment by buenaflor** [comment]
@romtsn @markushi looks like the reflection in the Android SDK is failing. One of the major difference we had from `7.10.1` to `7.11.0` is bumping the Android SDK from `6.29.0` to `6.32.0`. ~I can't reproduce it locally on my end but we'd need to wait for more information from the user I'd say.~ Can reproduce the logged error with debug mode but that seems like it's normal and it's not crashing the app.

**Comment by markushi** [comment]
We check if this class is available on app start [here](https://github.com/getsentry/sentry-java/blob/93a76ca3ed5e22b37a521784f4b601668bfa7e07/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L146-L147), which itself [prints an error log here](https://github.com/getsentry/sentry-java/blob/93a76ca3ed5e22b37a521784f4b601668bfa7e07/sentry-android-core/src/main/java/io/sentry/android/core/LoadClass.java#L24C19-L24C19).

So this is definitely not a crash, but maybe we simply shouldn't log this as an error.

**Comment by buenaflor** [comment]
This is now resolved. The user replied in the StackOverflow post mentioning that it did not indeed crash because of this but rather something else in their app.

**Comment by bruno-garcia** [comment]
Thanks for checking!
