### ISSUE TITLE
Outdated `Isar` model in flutter/example

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-dart#1810]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

denis@Deniss-MBP ios % flutter doctor -v
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64, locale de-AT)
    • Flutter version 3.16.5 on channel stable at /Users/denis/Repos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/denis/Library/Android/sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 13 Pro (mobile) • 00008110-000124A21138801E            • ios            • iOS 17.1.2 21B101
    • iPhone 15 Pro (mobile) • 6B9B6A68-2804-4447-9959-3CCAB49E9501 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 120.0.6099.199
    ! Error: Browsing on the local area network for iPhone 14. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad Pro. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth.
      (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.14.0

### Steps to Reproduce

1. Tap on button `isar`

### Expected Result

Isar spans/breadcrumbs are sent to sentry.io

### Actual Result

Error is thrown. This is based on the current `main` branch.

```
'package:isar/src/schema/collection_schema.dart': Failed assertion: line 24 pos 11: 'Isar.version == version': Outdated generate...
                       #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
                       #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
                       #2      new CollectionSchema (package:isar/src/schema/collection_schema.dart:24:11)
                       #3      UserSchema (package:sentry_flutter_example/isar/user.g.dart:16:20)
                       #4      UserSchema (package:sentry_flutter_example/isar/user.g.dart)
                       #5      MainScaffold.isarTest (package:sentry_flutter_example/main.dart:549:8)
                       <asynchronous suspension>
```

### Are you willing to submit a PR?

Yes

**Comment by denrase** [comment]
@buenaflor FYI

**Comment by denrase** [comment]
Tired running the Isar generator, which generated the exact same file. Upon running `pub get` the error was not present anymore. Closing until this becomes an issue again.
