### ISSUE TITLE
Android crashes when running SentryFlutter.init with latest ver.

### ISSUE THREAD

**Issue by Yokoi-K** [getsentry/sentry-dart#1981]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

<details><summary>flutter doctor -v</summary>

```

❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.3.1 23D60 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.5 on channel stable at /Users/yoko/.asdf/installs/flutter/3.19.5-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (13 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/yoko/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME =
      /Users/yoko/.zplug/repos/zplug/zplug/bin:/Users/yoko/.zplug/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/Library/Apple/usr/bin:/Users/yoko/fvm/default/bin:/Users/yoko/.pub-cache/bin:/Users/yoko/Library/Android/sdk/pl
      atform-tools:/Users/yoko/bin:/Users/yoko/Library/Android/sdk
    • ANDROID_SDK_ROOT =
      /Users/yoko/.zplug/repos/zplug/zplug/bin:/Users/yoko/.zplug/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/Library/Apple/usr/bin:/Users/yoko/fvm/default/bin:/Users/yoko/.pub-cache/bin:/Users/yoko/Library/Android/sdk/pl
      atform-tools:/Users/yoko/bin:/Users/yoko/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 8 Pro (mobile) • 37261FDJG006HT • android-arm64  • Android 14 (API 34)
    • macOS (desktop)      • macos          • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 110.0.5481.177
  
[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### Version

7.19.0

### Steps to Reproduce

When I run SentryFlutter.init on Android, I get the following error.

```
E/AndroidRuntime(14703): java.lang.NoSuchMethodError: No virtual method addIntegrationToSdkVersion()V in class Lio/sentry/android/fragment/FragmentLifecycleIntegration; or its super classes (declaration of 'io.sentry.android.fragment.FragmentLifecycleIntegration' appears in /data/app/~~XXXXXXXX-XXXXXXXXX==/app.example-XXXXXXXXXXX==/base.apk!classes2.dex)
E/AndroidRuntime(14703): 	at io.sentry.android.fragment.FragmentLifecycleIntegration.c(FragmentLifecycleIntegration.kt:34)
E/AndroidRuntime(14703): 	at io.sentry.k3.q(Sentry.java:117)
E/AndroidRuntime(14703): 	at io.sentry.k3.p(Sentry.java:10)
E/AndroidRuntime(14703): 	at io.sentry.android.core.n1.c(SentryAndroid.java:16)
E/AndroidRuntime(14703): 	at io.sentry.android.core.n1.d(SentryAndroid.java:6)
E/AndroidRuntime(14703): 	at io.sentry.flutter.SentryFlutterPlugin.initNativeSdk(SentryFlutterPlugin.kt:56)
E/AndroidRuntime(14703): 	at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.kt:216)
E/AndroidRuntime(14703): 	at oc.j$a.a(MethodChannel.java:18)
E/AndroidRuntime(14703): 	at cc.c.l(DartMessenger.java:19)
E/AndroidRuntime(14703): 	at cc.c.m(DartMessenger.java:42)
E/AndroidRuntime(14703): 	at cc.c.g(DartMessenger.java:1)
E/AndroidRuntime(14703): 	at cc.b.run(R8$$SyntheticClass:13)
E/AndroidRuntime(14703): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(14703): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14703): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(14703): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(14703): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(14703): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14703): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(14703): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

iOS is no problem.

### Expected Result

No more errors and successful execution.

### Actual Result

An error occurs.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, do you have any other sentry specific configuration? Such as using our gradle plugin?

**Comment by Yokoi-K** [comment]
Sorry, gradle description was wrong.
It worked fine!Thank you very much!

I have no problem to close this issue.

**Comment by feinstein** [comment]
@buenaflor I am getting this same error on 8.5.0 and gradle 4.10.0, can't I use the gradle plugin?

**Comment by feinstein** [comment]
Update, I had the sentry version defined in the gradle plugin. The old docs used to say it wasn't a problem, as it would ignore this version if a new one existed in the classpath, but I don't think this applies anymore.

**Comment by buenaflor** [comment]
How does your sentry gradle config look like? @feinstein

**Comment by feinstein** [comment]
I had this

```dart
 autoInstallation {
        enabled = true

        // Specifies a version of the sentry-android SDK and fragment, timber and okhttp integrations.
        //
        // This is also useful, when you have the sentry-android SDK already included into a transitive dependency/module and want to
        // align integration versions with it (if it's a direct dependency, the version will be inferred).
        //
        // NOTE: if you have a higher version of the sentry-android SDK or integrations on the classpath, this setting will have no effect
        // as Gradle will resolve it to the latest version.
        //
        // Defaults to the latest published Sentry version.
        sentryVersion = '6.28.0'
    }
```

While including  `sentry_flutter: 8.5.0` and `sentry_dart_plugin: ^2.1.0`

**Comment by buenaflor** [comment]
oh you're setting it to `6.28.0`, did you upgrade your sentry gradle plugin?

**Comment by feinstein** [comment]
Yeah, I think I did, but the docs led me to believe it would always pick the higher

**Comment by buenaflor** [comment]
Does it work if you remove it?

**Comment by feinstein** [comment]
Yes, that's what I did

**Comment by buenaflor** [comment]
@markushi do you maybe know more about why this might happen?
