### ISSUE TITLE
Error log about /system/xbin/which not found

### ISSUE THREAD

**Issue by dgilperez** [getsentry/sentry-dart#212]
On debug mode, on app startup, I am seeing this log: 

```
/Sentry  (24193): sentry-debug-meta.properties file was not found.
I/Sentry  (24193): Initializing SDK with DSN: 'https://xxxxx.ingest.sentry.io/xxxx'
D/Sentry  (24193): SU doesn't exist.
D/Sentry  (24193): java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
D/Sentry  (24193): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
D/Sentry  (24193): 	at java.lang.Runtime.exec(Runtime.java:698)
D/Sentry  (24193): 	at java.lang.Runtime.exec(Runtime.java:563)
D/Sentry  (24193): 	at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
D/Sentry  (24193): 	at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
D/Sentry  (24193): 	at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
D/Sentry  (24193): 	at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
D/Sentry  (24193): 	at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$NYQ5qA7CeWYLjnxHfVDRm7bpPQ0.call(Unknown Source:2)
D/Sentry  (24193): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/Sentry  (24193): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/Sentry  (24193): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/Sentry  (24193): 	at java.lang.Thread.run(Thread.java:919)
D/Sentry  (24193): Caused by: java.io.IOException: error=2, No such file or directory
D/Sentry  (24193): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
D/Sentry  (24193): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
D/Sentry  (24193): 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
D/Sentry  (24193): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
D/Sentry  (24193): 	... 11 more
```

It's not causing any crash apparently, but I'd prefer to double check before shipping it :) 

2. Include the output of the command `flutter doctor` below:

```sh
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
```

I am using alpha

```
  sentry_flutter: ^4.0.0-alpha.2
```

**Comment by marandaneto** [comment]
it's just noisy logging, we've removed it already from the Android SDK, we'll bump the Android SDK on the Flutter SDK asap, thanks for reporting :)

https://github.com/getsentry/sentry-java/pull/1059

**Comment by dgilperez** [comment]
Good. Shipping 🙈
