### ISSUE TITLE
Error while sending more throughout FlutterErrorDetails

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#242]
1. Please describe the issue and how to reproduce it, or link to a small reproducible application:
I'm trying to get a better and more details error report but I get the following exception
```
E/FileObserver(13655): Unhandled exception in FileObserver io.sentry.android.core.EnvelopeFileObserver@94251ab
E/FileObserver(13655): java.lang.IllegalArgumentException: Invalid envelope. Item at index '1'. has no header delimiter.
E/FileObserver(13655): 	at io.sentry.EnvelopeReader.read(EnvelopeReader.java:80)
E/FileObserver(13655): 	at io.sentry.OutboxSender.processFile(OutboxSender.java:60)
E/FileObserver(13655): 	at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:100)
E/FileObserver(13655): 	at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:58)
E/FileObserver(13655): 	at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
E/FileObserver(13655): 	at android.os.FileObserver$ObserverThread.observe(Native Method)
E/FileObserver(13655): 	at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)

```
To reproduce the issue checkout this [branch](https://github.com/ueman/sentry-dart/tree/feater/error-report)  and press the `Open Scaffold with UI error` button.

It only happens on Android, iOS works just fine.

2. Include the output of the command `flutter doctor` below:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

# Motivation

This change in the linked branch improve the error message from 
```
FlutterError
A RenderFlex overflowed by 1175 pixels on the right.
```
to
```

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 1175 pixels on the right.

The relevant error-causing widget was
Row
lib/scaffold_with_ui_error.dart:33
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#550f0 OVERFLOWING
════════════════════════════════════════════════════════════════════════════════
```

This is really helpful as it includes the class from which the error was thrown.

**Comment by marandaneto** [comment]
@ueman checking this out, thanks

**Comment by marandaneto** [comment]
ok a thing we should improve is: an event triggered by `FlutterError.onError` could have a null `errorDetails.stack` but more information in the `errorDetails` itself, I think this could even be a Flutter issue tbh, parsing the  `errorDetails` would be very flakey as the format could be very vast.

Logging `message: Message(detailedMessage)` would make sense though, but only if there's no `stack` I'd say.

Now back to the `Invalid envelope. Item at index '1'. has no header delimiter`, I believe it is because of the `detailedMessage` which has `\n` and we use that as a delimiter to read the next item, it'd be a sentry-android bug which I am debugging right now.

**Comment by ueman** [comment]
> Logging message: Message(detailedMessage) would make sense though, but only if there's no stack I'd say.

I do not think that works. 
The following code
```dart
import 'package:flutter/material.dart';

class ScaffoldWithUiError extends StatelessWidget {
    @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SecondaryScaffold'),
      ),
      body: Center(
        child: Column(
          children: [
            SizedBox(
              height: 500,
              width: 300,
              child: Builder(builder: (context) {
                return null;
              }),
            ),
            const Text(
              'You have added a navigation event '
              'to the crash reports breadcrumbs.',
            ),
            MaterialButton(
              child: const Text('Go back'),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
also raises an error through `FlutterError.onError`. But it has a stacktrace which looks like this:
<details>
 <summary>Stacktrace</summary>

```
FlutterError: A build function returned null.
The offending widget is:
  Builder
Build functions must never return null.
To return an empty space that causes the building widget to fill available room, return "Container()". To return an empty space that takes as little room as possible, return "Container(width: 0.0, height: 0.0)".
  File "debug.dart", line 302, col 7, in debugWidgetBuilderValue.<fn>
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 6236, col 32, in MultiChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 6118, col 14, in SingleChildRenderObjectElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4606, col 5, in ComponentElement._firstBuild
  File "framework.dart", line 4791, col 11, in StatefulElement._firstBuild
  File "framework.dart", line 4601, col 5, in ComponentElement.mount
  File "framework.dart", line 3569, col 14, in Element.inflateWidget
  File "framework.dart", line 3327, col 18, in Element.updateChild
  File "framework.dart", line 5705, col 32, in RenderObjectElement.updateChildren
  File "framework.dart", line 6246, col 17, in MultiChildRenderObjectElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4832, col 5, in StatefulElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4987, col 5, in ProxyElement.update
  File "inherited_notifier.dart", line 183, col 11, in _InheritedNotifierElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 6125, col 14, in SingleChildRenderObjectElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4832, col 5, in StatefulElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 6125, col 14, in SingleChildRenderObjectElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 6125, col 14, in SingleChildRenderObjectElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4708, col 5, in StatelessElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 4987, col 5, in ProxyElement.update
  File "framework.dart", line 3314, col 15, in Element.updateChild
  File "framework.dart", line 4652, col 16, in ComponentElement.performRebuild
  File "framework.dart", line 4800, col 11, in StatefulElement.performRebuild
  File "framework.dart", line 4343, col 5, in Element.rebuild
  File "framework.dart", line 2730, col 33, in BuildOwner.buildScope
  File "binding.dart", line 913, col 20, in WidgetsBinding.drawFrame
  File "binding.dart", line 302, col 5, in RendererBinding._handlePersistentFrameCallback
  File "binding.dart", line 1117, col 15, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1055, col 9, in SchedulerBinding.handleDrawFrame
  File "binding.dart", line 971, col 5, in SchedulerBinding._handleDrawFrame
  File "zone.dart", line 1190, col 13, in _rootRun
  File "zone.dart", line 1093, col 19, in _CustomZone.run
  File "zone.dart", line 997, col 7, in _CustomZone.runGuarded
  File "hooks.dart", line 251, col 10, in _invoke
  File "hooks.dart", line 209, col 3, in _drawFrame
```

</details>

while the `detailedMessage` looks like this
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown building Builder(dirty):
A build function returned null.
The offending widget is:
  Builder
Build functions must never return null.
To return an empty space that causes the building widget to fill
available room, return "Container()". To return an empty space
that takes as little room as possible, return "Container(width:
0.0, height: 0.0)".

The relevant error-causing widget was:
  Builder
  file:///Users/jonas/Documents/projects/sentry-dart/flutter/example/lib/scaffold_with_ui_error.dart:36:22

When the exception was thrown, this was the stack:
#0      debugWidgetBuilderValue.<anonymous closure> (package:flutter/src/widgets/debug.dart:302:7)
#1      debugWidgetBuilderValue (package:flutter/src/widgets/debug.dart:323:4)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4632:7)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
...     Normal element mounting (4 frames)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#10     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
...     Normal element mounting (22 frames)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
...     Normal element mounting (100 frames)
#133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#134    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
...     Normal element mounting (136 frames)
#270    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#271    Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
#272    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5705:32)
#273    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#274    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#275    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#276    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#277    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#278    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#279    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#280    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#281    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#282    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#283    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
#284    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#285    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#288    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#289    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#290    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#291    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#292    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#294    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#295    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#296    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#297    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#298    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#299    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#300    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#301    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#302    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#303    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#304    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#305    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#306    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#307    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#308    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#309    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#310    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#311    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#312    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#316    _invoke (dart:ui/hooks.dart:251:10)
#317    _drawFrame (dart:ui/hooks.dart:209:3)
(elided 3 frames from dart:async)

═════════════════════════════════════════════════════════════════
```

Note that the `detailedMessage` is once more, more helpful than the stacktrace.

**Comment by marandaneto** [comment]
@ueman so would you say that we should log the `errorDetails.toString()` every time? not sure how big messages can be, we have a limit of 200kb per event btw (iirc).

I believe the stack trace should be either better than the message or at least equal otherwise I'd consider also raising an issue to the Flutter team, otherwise it'd be hard for error monitoring tools to find out the best approach for every type of error.

**Comment by marandaneto** [comment]
@ueman ok I found out:

Flutter adds some special chars that break our current envelope parsing.

```
      var detailedMessage = errorDetails.toString();
      detailedMessage = errorDetails.toString().replaceAll('◢', '-');
      detailedMessage = detailedMessage.replaceAll('◤', '-');
      detailedMessage = detailedMessage.replaceAll('═', '=');
      detailedMessage = detailedMessage.replaceAll('╡', '|');
      detailedMessage = detailedMessage.replaceAll('╞', '|');
```

would be a workaround, for now, I'll check whether I have to fix this, either on sentry-android or sentry-dart.

**Comment by ueman** [comment]
Hm, I'm not sure. Previously I just reported `errorDetails.toString()` and that worked just fine for me. 

The [FlutterErrorDetails.toString()](https://api.flutter.dev/flutter/foundation/FlutterErrorDetails/toString.html) can take a [DiagnosticLevel](https://api.flutter.dev/flutter/foundation/DiagnosticLevel-class.html). It could be enough to just call `errorDetails.toString(minLevel: DiagnosticLevel.debug)` or so. Also the DiagnosticLevel docs say the following:

> In release mode, this level may not have any effect, as diagnostics in release mode are compacted or truncated to reduce binary size.


Raising an issue to the Flutter team would be helpful, they should know how to get good error messages.

I think the stacktrace or error message of FlutterErrors should always include 
```
The relevant error-causing widget was:
  Builder
  lib/scaffold_with_ui_error.dart:36:22
```
as this is really helpful.

EDIT:
Just for reference, the file location is contained in an element of [FlutterError.diagnostics](https://api.flutter.dev/flutter/foundation/FlutterError/diagnostics.html)

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/4.0.1

I'll consider the improvements also discussed here in another PR, thanks for raising this @ueman
