### ISSUE TITLE
Sentry Upgrade in flutter causing other testcases to fail.

### ISSUE THREAD

**Issue by pvermaDM** [getsentry/sentry-dart#2483]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I am trying to upgrade from sentry_flutter: ^7.17.0 to sentry_flutter: ^8.3.0.

and it is causing failure in our test cases for GoRouter.

### How are you getting stuck?

i am getting this error, when running the test cases for our GoRouter

With this error,

```
Pending timers:
Timer (duration: 0:00:30.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
getsentry/sentry#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
getsentry/sentry#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
getsentry/sentry#6      NativeAppStartIntegration.getAppStartInfo (package:sentry_flutter/src/integrations/native_app_start_integration.dart:51:10)
getsentry/sentry#7      SentryNavigatorObserver._startTimeToDisplayTracking (package:sentry_flutter/src/navigation/sentry_navigator_observer.dart:335:62)
getsentry/sentry#8      SentryNavigatorObserver.didPush (package:sentry_flutter/src/navigation/sentry_navigator_observer.dart:155:5)
getsentry/sentry#9      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:3372:14)
getsentry/sentry#10     List.forEach (dart:core-patch/growable_array.dart:416:8)

.......

The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1527 pos 12: '!timersPending'
```

### Where in the product are you?

Other

**Comment by aldy505** [comment]
@dalnoki Hi, this should be transferred to https://github.com/getsentry/sentry-dart instead. The issue has nothing to do with self-hosted, we can't do anything about this.

**Comment by buenaflor** [comment]
hi this issue should be fixed in the newest versions

**Comment by buenaflor** [comment]
Closing this, let us know if there are still issues
