### ISSUE TITLE
NullPointerException for exceptions generated by android ndk c++ code

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#386]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
no problems

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

Thanks for the lib! I try to capture an exception manually in android ndk (c++) code like this:

```
        sentry_value_t exc = sentry_value_new_object();
        sentry_value_set_by_key(exc, "type", sentry_value_new_string("Exception"));
        sentry_value_set_by_key(exc, "value", sentry_value_new_string("myerror"));

        sentry_value_t event = sentry_value_new_event();
        sentry_value_set_by_key(event, "exception", exc);
        sentry_capture_event(event);
```

but then error occurs:

```
2021-03-26 08:34:15.561 20920-21009/com.cjy.yplusplus E/Sentry: Error while capturing event with id: f8940f9a7dda40dc4fd1f11070fe1d22
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at io.sentry.SentryEvent.isCrashed(SentryEvent.java:346)
        at io.sentry.SentryClient.lambda$updateSessionData$0$SentryClient(SentryClient.java:268)
        at io.sentry.-$$Lambda$SentryClient$95WLIRfJlDw7w3H0oQsRkrt03kA.accept(Unknown Source:6)
        at io.sentry.Scope.withSession(Scope.java:598)
        at io.sentry.SentryClient.updateSessionData(SentryClient.java:264)
        at io.sentry.SentryClient.captureEvent(SentryClient.java:81)
        at io.sentry.Hub.captureEvent(Hub.java:82)
        at io.sentry.Sentry.captureEvent(Sentry.java:254)
        at io.sentry.HubAdapter.captureEvent(HubAdapter.java:27)
        at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:141)
        at io.sentry.OutboxSender.processFile(OutboxSender.java:68)
        at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:101)
        at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:59)
        at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
        at android.os.FileObserver$ObserverThread.observe(Native Method)
        at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
```

**EDIT:**

I tried to write this hacky code. Is it correct?

```
        // SentryException
        sentry_value_t exc = sentry_value_new_object();
        sentry_value_set_by_key(exc, "type", sentry_value_new_string("Exception"));
        sentry_value_set_by_key(exc, "value", sentry_value_new_string(oss.str().c_str()));

        // List<SentryException> values;
        sentry_value_t values_list = sentry_value_new_list();
        sentry_value_append(values_list, exc);

        // SentryValues<SentryException> exception;
        sentry_value_t exception_obj = sentry_value_new_object();
        sentry_value_set_by_key(exception_obj, "values", values_list);

        // SentryEvent event;
        sentry_value_t event = sentry_value_new_event();
        sentry_value_set_by_key(event, "exception", exception_obj);
        sentry_capture_event(event);
```

**Comment by marandaneto** [comment]
@fzyzcjy `values` should be a list and not a `sentry_value_new_object`

https://develop.sentry.dev/sdk/event-payloads/exception/ and https://develop.sentry.dev/sdk/event-payloads/exception/#examples so you have to use `sentry_value_new_list()`

https://github.com/getsentry/sentry-native/blob/master/src/backends/sentry_backend_inproc.c#L173-L241 for some inspiration

**Comment by fzyzcjy** [comment]
@marandaneto Thanks, actually it seems that the official doc is wrong (outdated?)

**Comment by marandaneto** [comment]
@fzyzcjy which part? I checked the shared links above and they look like correct

**Comment by fzyzcjy** [comment]
@marandaneto 

this: https://docs.sentry.io/platforms/native/usage/#capturing-errors

```
#include <sentry.h>

sentry_value_t exc = sentry_value_new_object();
sentry_value_set_by_key(exc, "type", sentry_value_new_string("Exception"));
sentry_value_set_by_key(exc, "value", sentry_value_new_string("Error message."));

sentry_value_t event = sentry_value_new_event();
sentry_value_set_by_key(event, "exception", exc);
sentry_capture_event(event);
```

**Comment by marandaneto** [comment]
@fzyzcjy indeed, here we go https://github.com/getsentry/sentry-docs/pull/3323
thanks for pointing out!

**Comment by fzyzcjy** [comment]
@marandaneto You are welcome
