### ISSUE TITLE
Unhandled Exception: LateInitializationError: Field '_receivePort@1710301534' has not been initialized.

### ISSUE THREAD

**Issue by HugoSart** [getsentry/sentry-dart#508]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [X]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed) // OBS: Android Studio is installed but not recognized by this command for some reason
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (3 available)
```

The version of the SDK (See pubspec.lock):
**5.1.0**

---
I have the following issue:

When I try to reinitizalize the Sdk with different parameters, I get the following error:
```
E/flutter (13798): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_receivePort@1710301534' has not been initialized.
E/flutter (13798): #0      IsolateErrorIntegration._receivePort (package:sentry/src/isolate_error_integration.dart)
E/flutter (13798): #1      IsolateErrorIntegration.close (package:sentry/src/isolate_error_integration.dart:26:5)
E/flutter (13798): #2      Hub.close (package:sentry/src/hub.dart:234:27)
E/flutter (13798): #3      Sentry._init (package:sentry/src/sentry.dart:104:17)
E/flutter (13798): <asynchronous suspension>
E/flutter (13798): #4      Sentry.init (package:sentry/src/sentry.dart:55:5)
E/flutter (13798): <asynchronous suspension>
E/flutter (13798): #5      SentryService._initializeClient (package:itini/core/services/sentry_service.dart:139:5)
E/flutter (13798): <asynchronous suspension>
```

**Steps to reproduce:**
1. Initialize SDK;
2. Close SDK;
3. Initialize SDK;

**Actual result:**
LateInitializationError is thrown.

**Expected result:**
No errors thrown.

**Comment by ueman** [comment]
Thanks for filing this issue.
What exactly is your use case that you need to init, close and init the SDK again?

**Comment by HugoSart** [comment]
In my case, I didn't find a proper way to edit the `environment` property without reinitializing the SDK (please, tell me if there is an easier way to do so). But once I worked on a project that we had two Sentry projects: one for production and one for staging (there was a switch in the app to change the backend being used at runtime). So, I think in the last case a reinitialization to change the DSN would be necessary.

**Comment by ueman** [comment]
@denrase Does this happen in the Sentry app, too?
I imagine it should, if you're toggling the SDK in the settings.

I'm also kinda suspect that one shouldn't use the appRunner callback (and thus don't use the IsolateIntegration) if you're toggling the SDK.

**Comment by HugoSart** [comment]
@ueman I'm not using the appRunner parameter to run my application.

**Comment by marandaneto** [comment]
@ueman I believe `NativeSdkIntegration` can happen the same if `close` throws, `_options` might not be inited yet.
can you check that too? thanks

**Comment by denrase** [comment]
@ueman Just tied to repoduce this in the Sentry Mobile app by disableing and enabling multiple times form the Settings. Not seeing this error in the logs so far.

Close

```
D/Sentry  ( 5473): UncaughtExceptionHandlerIntegration removed.
D/sentry-native( 5473): shutting down backend
D/Sentry  ( 5473): NdkIntegration removed.
D/Sentry  ( 5473): EnvelopeFileObserverIntegration removed.
D/Sentry  ( 5473): AppLifecycleIntegration removed.
D/Sentry  ( 5473): ActivityLifecycleIntegration removed.
D/Sentry  ( 5473): AppComponentsBreadcrumbsIntegration removed.
D/Sentry  ( 5473): SystemEventsBreadcrumbsIntegration remove.
D/Sentry  ( 5473): TempSensorBreadcrumbsIntegration removed.
I/Sentry  ( 5473): Closing SentryClient.
D/Sentry  ( 5473): Shutting down
```

Re-Enable

```
D/FlutterSecureStoragePl( 5473): StorageCipher already initialized
I/Sentry  ( 5473): Initializing SDK with DSN: 'https://b647bf95c35249fe967c91feae3f72d7@o447951.ingest.sentry.io/5555613'
I/Sentry  ( 5473): GlobalHubMode: 'true'
I/Sentry  ( 5473): sentry-debug-meta.properties file was not found.
D/Sentry  ( 5473): UncaughtExceptionHandlerIntegration enabled: true
D/Sentry  ( 5473): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
D/Sentry  ( 5473): UncaughtExceptionHandlerIntegration installed.
D/Sentry  ( 5473): ShutdownHookIntegration installed.
D/Sentry  ( 5473): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  ( 5473): NdkIntegration enabled: true
D/Sentry  ( 5473): Started processing cached files from /data/user/0/io.sentry.mobile.app/cache/sentry
D/Sentry  ( 5473): Processing dir. /data/user/0/io.sentry.mobile.app/cache/sentry
I/sentry-native( 5473): using database path "/data/data/io.sentry.mobile.app/cache/sentry/.sentry-native"
D/Sentry  ( 5473): Processing 0 items from cache dir /data/user/0/io.sentry.mobile.app/cache/sentry
D/Sentry  ( 5473): File /data/user/0/io.sentry.mobile.app/cache/sentry/outbox is not a File.
D/Sentry  ( 5473): File /data/user/0/io.sentry.mobile.app/cache/sentry/.sentry-native is not a File.
D/Sentry  ( 5473): Processing file: /data/user/0/io.sentry.mobile.app/cache/sentry/session.json
D/sentry-native( 5473): starting backend
D/Sentry  ( 5473): File '/data/user/0/io.sentry.mobile.app/cache/sentry/session.json' doesn't match extension expected.
D/Sentry  ( 5473): NdkIntegration installed.
D/Sentry  ( 5473): Finished processing cached files from /data/user/0/io.sentry.mobile.app/cache/sentry
D/Sentry  ( 5473): Registering EnvelopeFileObserverIntegration for path: /data/user/0/io.sentry.mobile.app/cache/sentry/outbox
D/Sentry  ( 5473): EnvelopeFileObserverIntegration installed.
D/Sentry  ( 5473): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  ( 5473): AnrIntegration enabled: false
D/Sentry  ( 5473): enableSessionTracking enabled: true
D/Sentry  ( 5473): Started processing cached files from /data/user/0/io.sentry.mobile.app/cache/sentry/outbox
D/Sentry  ( 5473): enableAppLifecycleBreadcrumbs enabled: true
D/Sentry  ( 5473): Processing dir. /data/user/0/io.sentry.mobile.app/cache/sentry/outbox
D/Sentry  ( 5473): SU isn't found on this Device.
D/Sentry  ( 5473): Processing 0 items from cache dir /data/user/0/io.sentry.mobile.app/cache/sentry/outbox
D/Sentry  ( 5473): Finished processing cached files from /data/user/0/io.sentry.mobile.app/cache/sentry/outbox
D/Sentry  ( 5473): AppLifecycleIntegration installed.
D/Sentry  ( 5473): ActivityLifecycleIntegration enabled: true
D/Sentry  ( 5473): ActivityLifecycleIntegration installed.
D/Sentry  ( 5473): AppComponentsBreadcrumbsIntegration enabled: true
D/Sentry  ( 5473): AppComponentsBreadcrumbsIntegration installed.
D/Sentry  ( 5473): SystemEventsBreadcrumbsIntegration enabled: true
W/Sentry  ( 5473): Current session is not ended, we'd need to end it.
D/Sentry  ( 5473): SystemEventsBreadcrumbsIntegration installed.
D/Sentry  ( 5473): enableSystemEventsBreadcrumbs enabled: true
W/pool-9-thread-1( 5473): type=1400 audit(0.0:43): avc: denied { read } for name="version" dev="proc" ino=4026532035 scontext=u:r:untrusted_app:s0:c156,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=io.sentry.mobile.app
D/Sentry  ( 5473): TempSensorBreadcrumbsIntegration installed.
D/Sentry  ( 5473): enableSystemEventBreadcrumbs enabled: true
D/Sentry  ( 5473): Serializing object: {"sid":"2c5fd4e0-3d21-420d-8a18-97bfeb1cf099","did":"e8f915b2-e54e-4dba-96dd-26b03e76e9b3","started":"2021-06-29T12:47:26.918Z","status":"exited","seq":1624970870058,"duration":23.14,"timestamp":"2021-06-29T12:47:50.058Z","attrs":{"release":"io.sentry.mobile.app@1.0.2+22","environment":"debug"}}
D/Sentry  ( 5473): Serializing object: {"sid":"0c9710b6-c793-47dd-8664-a0740e07a208","did":"e8f915b2-e54e-4dba-96dd-26b03e76e9b3","init":true,"started":"2021-06-29T12:47:50.050Z","status":"ok","timestamp":"2021-06-29T12:47:50.050Z","attrs":{"release":"io.sentry.mobile.app@1.0.2+22","environment":"debug"}}
[sentry] [debug] release: io.sentry.mobile.app@1.0.2+22
D/Sentry  ( 5473): Serializing object: {"sid":"0c9710b6-c793-47dd-8664-a0740e07a208","did":"e8f915b2-e54e-4dba-96dd-26b03e76e9b3","init":true,"started":"2021-06-29T12:47:50.050Z","status":"ok","timestamp":"2021-06-29T12:47:50.050Z","attrs":{"release":"io.sentry.mobile.app@1.0.2+22","environment":"debug"}}
D/Sentry  ( 5473): Adding Envelope to offline storage: /data/user/0/io.sentry.mobile.app/cache/sentry/6f354802-660f-4a64-a1e2-d15b1da2383c.envelope
D/Sentry  ( 5473): Envelope sent successfully.
D/Sentry  ( 5473): Discarding envelope from cache: /data/user/0/io.sentry.mobile.app/cache/sentry/6f354802-660f-4a64-a1e2-d15b1da2383c.envelope
D/Sentry  ( 5473): Envelope flushed
```

Re-Close

```
D/Sentry  ( 5473): UncaughtExceptionHandlerIntegration removed.
D/sentry-native( 5473): shutting down backend
D/Sentry  ( 5473): NdkIntegration removed.
D/Sentry  ( 5473): EnvelopeFileObserverIntegration removed.
D/Sentry  ( 5473): AppLifecycleIntegration removed.
D/Sentry  ( 5473): ActivityLifecycleIntegration removed.
D/Sentry  ( 5473): AppComponentsBreadcrumbsIntegration removed.
D/Sentry  ( 5473): SystemEventsBreadcrumbsIntegration remove.
D/Sentry  ( 5473): TempSensorBreadcrumbsIntegration removed.
I/Sentry  ( 5473): Closing SentryClient.
D/Sentry  ( 5473): Shutting down
```
