### ISSUE TITLE
Incorrect serialization of TargetPlatform prevents error from being tracked

### ISSUE THREAD

**Issue by venkatd** [getsentry/sentry-dart#521]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

<details>
    <summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.3.0-2.0.pre.234, on Mac OS X 10.14.6 18G8022
    darwin-x64, locale en-US)
    • Flutter version 2.3.0-2.0.pre.234 at /Users/venkat/code/flutter
    • Upstream repository unknown
    • Framework revision 89442b495e (8 weeks ago), 2021-05-14 21:34:02 -0700
    • Engine revision 3c1d96f0b8
    • Dart version 2.14.0 (build
      2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/venkat/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.0.1
    • Dart plugin version 201.9335

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.14.6 18G8022
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```
</details>

The version of the SDK (See pubspec.lock):
**6.0.0-beta.1**

---
I have the following issue:

Exceptions don't get captured because serialization fails on the TargetPlatform enum:
https://github.com/getsentry/sentry-dart/blob/b9866b750e892f4283fd8cbcd9b9625ad7821e77/flutter/lib/src/flutter_enricher_event_processor.dart#L126

**Steps to reproduce:**
Capture any exception on MacOS/iOS/Android

**Actual result:**
The following exception:
```
         Converting object to an encodable object failed: Instance of 'TargetPlatform'
         #0      _JsonStringifier.writeObject (dart:convert/json.dart:688:7)
         #1      _JsonStringifier.writeMap (dart:convert/json.dart:769:7)
         #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
         #3      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
         #4      _JsonStringifier.writeMap (dart:convert/json.dart:769:7)
         #5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
         #6      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
         #7      _JsonStringifier.writeMap (dart:convert/json.dart:769:7)
         #8      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
         #9      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
         #10     _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)
         #11     _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
         #12     JsonEncoder.convert (dart:convert/json.dart:262:30)
         #13     JsonCodec.encode (dart:convert/json.dart:172:45)
         #14     jsonEncode (dart:convert/json.dart:81:10)
         #15     new SentryEnvelopeItem.fromEvent.<anonymous closure> (package:sentry/src/sentry_envelope_item.dart:20:27)
         #16     new SentryEnvelopeItem.fromEvent.<anonymous closure> (package:sentry/src/sentry_envelope_item.dart:19:36)
         #17     _CachedItem.getData (package:sentry/src/sentry_envelope_item.dart:49:33)
         #18     new SentryEnvelopeItem.fromEvent.<anonymous closure> (package:sentry/src/sentry_envelope_item.dart:25:32)
         #19     new SentryEnvelopeItem.fromEvent.<anonymous closure> (package:sentry/src/sentry_envelope_item.dart:24:23)
         #20     SentryEnvelopeItemHeader.toJson (package:sentry/src/sentry_envelope_item_header.dart:26:34)
         #21     SentryEnvelopeItem.envelopeItemStream (package:sentry/src/sentry_envelope_item.dart:36:47)
         <asynchronous suspension>
         #22     SentryEnvelope.envelopeStream (package:sentry/src/sentry_envelope.dart:30:7)
         <asynchronous suspension>
         #23     Stream.forEach.<anonymous closure> (dart:async/stream.dart)
         <asynchronous suspension>
```

**Expected result:**
Expect the payload to get serialized properly.

**This should be surrounded in a `describeEnum` to avoid a serialization error.**

**Comment by ueman** [comment]
A fix is already being worked on in https://github.com/getsentry/sentry-dart/pull/520
Thanks for raising an issue.

**Comment by ueman** [comment]
Closed by https://github.com/getsentry/sentry-dart/pull/520
