### ISSUE TITLE
1000s logs/second about network or external storage

### ISSUE THREAD

**Issue by matejkramny** [getsentry/sentry-dart#564]
_Platform:_
- [x]  Flutter Android or iOS

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev

The version of the SDK (See pubspec.lock):
5.1.0

---

"Not possible to read external files directory"

![Screenshot_20210822_105239](https://user-images.githubusercontent.com/797608/130350671-7053a74d-1e63-4350-a185-dafa3be2e9aa.png)

This is one device, span of 24h. It's running Android 10, Lenovo TB-X505F.

---

The histogram legend shows ~3500 messages in the span of one second.

![Screenshot_20210821_154031](https://user-images.githubusercontent.com/797608/130325412-64b59bc7-855e-403f-8c77-d058171d2161.png)

Comes from an Android 9, Lenovo TB-7305F

This one is quite concerning since it seems to be stuck in some loop aggressively checking for connectivity.

**Comment by marandaneto** [comment]
> Not possible to read external files directory

it's just a debug logging, which means the device didn't have an external sdcard.

if you run a Flutter App/ on debug mode, Sentry debug mode is enabled by default, that's why you see such logs, you shouldn't if running on release mode.

> This one is quite concerning since it seems to be stuck in some loop aggressively checking for connectivity.

that's indeed concerning since this check is only called when an event is captured, and sentry itself does not capture events in a tight loop, what else do you see in the logs? can you provide a reproducible example? I don't experience this when running our examples, thanks

**Comment by marandaneto** [comment]
@matejkramny any news?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by akul1994** [comment]
Happening for me too, getting more than 1000 logs a second in debug builds, this is making it impossible for me to actually filter out useful logs, event tried by setting debug to false while initialising

`eHint.waitFlush(DirectoryProcessor.java:105)
        at io.sentry.OutboxSender.waitFlush(OutboxSender.java:245)
        at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:137)
        at io.sentry.OutboxSender.processFile(OutboxSender.java:70)
        at io.sentry.DirectoryProcessor.processDirectory(DirectoryProcessor.java:66)
        at io.sentry.OutboxSender.processDirectory(OutboxSender.java:29)
        at io.sentry.SendCachedEnvelopeFireAndForgetIntegration$SendFireAndForgetFactory$-CC.lambda$processDir$0(SendCachedEnvelopeFireAndForgetIntegration.java:42)
        at io.sentry.-$$Lambda$SendCachedEnvelopeFireAndForgetIntegration$SendFireAndForgetFactory$0LBM9z6C34iFlGwSY7l9z84nZSY.send(Unknown Source:8)
        at io.sentry.SendCachedEnvelopeFireAndForgetIntegration.lambda$register$0(SendCachedEnvelopeFireAndForgetIntegration.java:79)
        at io.sentry.-$$Lambda$SendCachedEnvelopeFireAndForgetIntegration$MeVfZg8XM9fBl32kxrltlaaZLh0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-09-28 18:50:51.000 7549-10890/com.tresscommas.threedots.stage W/Sentry: Timed out waiting for event id submission: 28ac309cf8b94c3383e6a6ac18b7eb2b
2021-09-28 18:50:51.000 7549-10890/com.tresscommas.threedots.stage D/Sentry: File '/data/user/0/com.tresscommas.threedots.stage/cache/sentry/outbox/377ad869-97c2-4297-a782-8d9ec0c9598e' is done.
2021-09-28 18:50:51.002 7549-10890/com.tresscommas.threedots.stage D/Sentry: Failed to delete: /data/user/0/com.tresscommas.threedots.stage/cache/sentry/outbox/377ad869-97c2-4297-a782-8d9ec0c9598e
2021-09-28 18:50:51.002 7549-10890/com.tresscommas.threedots.stage D/Sentry: File /data/user/0/com.tresscommas.threedots.stage/cache/sentry/outbox/546d6b60-22e0-493c-a10d-efa6b11cdf75 is not a File.
2021-09-28 18:50:51.003 7549-11278/com.tresscommas.threedots.stage I/Sentry: Not possible to read external files directory
2021-09-28 18:50:51.003 7549-10890/com.tresscommas.threedots.stage D/Sentry: File /data/user/0/com.tresscommas.threedots.stage/cache/sentry/outbox/814af9ed-ff3a-43c0-91c6-d6897be8409c is not a File.
2021-09-28 18:50:51.003 7549-10890/com.tresscommas.threedots.stage D/Sentry: Processing file: /data/user/0/com.tresscommas.threedots.stage/cache/sentry/outbox/ee86d2ec-599a-473b-9455-3e4bc1dbebd8`

**Comment by akul1994** [comment]
@marandaneto please help

**Comment by akul1994** [comment]
even get these error logs

`2021-09-28 18:52:37.564 7549-10638/com.tresscommas.threedots.stage E/Sentry: Exception while awaiting on lock.
    java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1350)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
        at io.sentry.DirectoryProcessor$SendCachedEnvelopeHint.waitFlush(DirectoryProcessor.java:105)
        at io.sentry.OutboxSender.waitFlush(OutboxSender.java:245)
        at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:137)
        at io.sentry.OutboxSender.processFile(OutboxSender.java:70)
        at io.sentry.DirectoryProcessor.processDirectory(DirectoryProcessor.java:66)
        at io.sentry.OutboxSender.processDirectory(OutboxSender.java:29)
        at io.sentry.SendCachedEnvelopeFireAndForgetIntegration$SendFireAndForgetFactory$-CC.lambda$processDir$0(SendCachedEnvelopeFireAndForgetIntegration.java:42)
        at io.sentry.-$$Lambda$SendCachedEnvelopeFireAndForgetIntegration$SendFireAndForgetFactory$0LBM9z6C34iFlGwSY7l9z84nZSY.send(Unknown Source:8)
        at io.sentry.SendCachedEnvelopeFireAndForgetIntegration.lambda$register$0(SendCachedEnvelopeFireAndForgetIntegration.java:79)
        at io.sentry.-$$Lambda$SendCachedEnvelopeFireAndForgetIntegration$MeVfZg8XM9fBl32kxrltlaaZLh0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by marandaneto** [comment]
@akul1994 can you set up a sample project that reproduces the issue and upload it to github? since I can't reproduce myself.
