### ISSUE TITLE
[sentry] [error] Failed to save envelope

### ISSUE THREAD

**Issue by apgiorgi** [getsentry/sentry-dart#582]
_Platform:_
- [X]  Flutter Android or iOS

_IDE:_
- [X]  VSCode

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [X]  Enabled

_Platform installed with:_
- [X] pub.dev

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.14.6 18G9216 darwin-x64, locale en-CH)
    • Flutter version 2.2.3 at -------
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at ------
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63
```

The version of the SDK (See pubspec.lock):
6.0.0

---
I have the following issue:

After upgrading from 5.1.0 to 6.0.0, I started to receive this Sentry error when it tries to "collect" an app error:

```
[sentry] [error] Failed to save envelope
[sentry] PlatformException (PlatformException(error, byte[] cannot be cast to java.lang.String, null, java.lang.ClassCastException: byte[] cannot be cast to java.lang.String
           	at io.sentry.flutter.SentryFlutterPlugin.captureEnvelope(SentryFlutterPlugin.kt:125)
           	at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.kt:34)
           	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
           	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
           	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
           	at android.os.MessageQueue.nativePollOnce(Native Method)
           	at android.os.MessageQueue.next(MessageQueue.java:336)
           	at android.os.Looper.loop(Looper.java:174)
           	at android.app.ActivityThread.main(ActivityThread.java:7356)
           	at java.lang.reflect.Method.invoke(Native Method)
           	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
           	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
           ))

[sentry] #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
           <asynchronous suspension>
#2      FileSystemTransport.send
package:sentry_flutter/src/file_system_transport.dart:19
           <asynchronous suspension>
#3      SentryClient.captureEvent
package:sentry/src/sentry_client.dart:117
           <asynchronous suspension>
#4      Hub.captureEvent
package:sentry/src/hub.dart:73
           <asynchronous suspension>
#5      RunZonedGuardedIntegration.call.<anonymous closure>
package:sentry/src/default_integrations.dart:39
           <asynchronous suspension>
```

**Steps to reproduce:**
- Build a flutter app that will generate an error
- install flutter 5.1.0
- catch the error successfully
- update sentry to 6.0.0
- try reproducing the app error

**Actual result:**
- Sentry is crashing

**Expected result:**
- Sentry would correctly catch the error and send it to the cloud

**Comment by marandaneto** [comment]
@apgiorgi thanks for reporting.
I guess you have outdated deps. since we don't use String for `captureEnvelope` but rather `byte[]` and the cast does not exist anymore, try to run `flutter pub outdated` and `flutter pub upgrade`, let us know, thanks

**Comment by marandaneto** [comment]
@apgiorgi hey, any news?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by apgiorgi** [comment]
Hi @marandaneto,

I'm sorry for the late delay.

You were right. It was some weird conflict in the project.

Thanks for the support!
