### ISSUE TITLE
Clear and Readable stack trace on Flutter web, or dart compiled in JS in general

### ISSUE THREAD

**Issue by jaumard** [getsentry/sentry-dart#630]
The sentry reports for flutter web are unreadable and not helpful at all ^^ 
Example: 
``` 
minified:f2: DioError [DioErrorType.response]: XMLHttpRequest error.
rM@https://213.32.91.117:3000/main.dart.js:16988:33
aAJ@https://213.32.91.117:3000/main.dart.js:25439:17
@https://213.32.91.117:3000/main.dart.js:45731:8
@https://213.32.91.117:3000/main.dart.js:15690:63
$2@https://213.32.91.117:3000/main.dart.js:38143:15
$2@https://213.32.91.117:3000/main.dart.js:38140:18
axv@https://213.32.91.117:3000/main.dart.js:15947:21
@https://213.32.91.117:3000/main.dart.js:90746:73
By@https://213.32.91.117:3000/main.dart.js:39248:14
ao7@https://213.32.91.117:3000/main.dart.js:38400:20
$0@https://213.32.91.117:3000/main.dart.js:38555:40
xJ@https://213.32.91.117:3000/main.dart.js:15810:80
fj@https://213.32.91.117:3000/main.dart.js:38471:5
$0@https://213.32.91.117:3000/main.dart.js:38518:15
axu@https://213.32.91.117:3000/main.dart.js:15938:11
@https://213.32.91.117:3000/main.dart.js:90744:69
p8@https://213.32.91.117:3000/main.dart.js:39244:14
l7@https://213.32.91.117:3000/main.dart.js:39219:12
$0@https://213.32.91.117:3000/main.dart.js:39292:22
b0p@https://213.32.91.117:3000/main.dart.js:15842:7
b0W@https://213.32.91.117:3000/main.dart.js:15844:10
$1@https://213.32.91.117:3000/main.dart.js:38087:5
b2I@https://213.32.91.117:3000/main.dart.js:10092:19
@https://213.32.91.117:3000/main.dart.js:10100:52
  at b(main.dart.js:10011:12)
  at $2(main.dart.js:45878:10)
  at axv(main.dart.js:15947:21)
  at <fn>(main.dart.js:90746:73)
  at By(main.dart.js:39248:14)
  at ao7(main.dart.js:38400:20)
  at $0(main.dart.js:38555:40)
  at xJ(main.dart.js:15810:80)
  at fj(main.dart.js:38471:5)
  at fj(main.dart.js:38395:18)
  at hY(main.dart.js:38383:8)
  at $2(main.dart.js:38369:23)
  at axv(main.dart.js:15947:21)
  at <fn>(main.dart.js:90746:73)
  at By(main.dart.js:39248:14)
  at ao7(main.dart.js:38400:20)
  at $0(main.dart.js:38555:40)
  at xJ(main.dart.js:15810:80)
  at fj(main.dart.js:38471:5)
  at $0(main.dart.js:38518:15)
  at axu(main.dart.js:15938:11)
  at <fn>(main.dart.js:90744:69)
  at p8(main.dart.js:39244:14)
  at l7(main.dart.js:39219:12)
  at $0(main.dart.js:39292:22)
  at b0p(main.dart.js:15842:7)
  at b0W(main.dart.js:15844:10)
  at $1(main.dart.js:38087:5)
  at b2I(main.dart.js:10092:19)
  at <fn>(main.dart.js:10100:52)
```

Here is two packages that could help with that and remap compiled JS stack trace to readable dart stacktrace. 

https://pub.dev/packages/source_maps
lets you load the map file produced by flutter web
https://pub.dev/packages/source_map_stack_trace
will map a javascript stack trace back to dart

If sentry can do the job under the hood so we can have meaningful reports it would be awesome.

**Comment by marandaneto** [comment]
yep, we already do it, 
https://docs.sentry.io/platforms/flutter/upload-debug/#sentry-dart-plugin
https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-source-maps-for-flutter-web

**Comment by jaumard** [comment]
Ha ha amazing ^^ sorry I miss that! Thanks a lot! I'll take a look :)
