### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by OHeroJ** [getsentry/sentry-dart#918]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [d] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 11.6.5 20G527 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

The version of the SDK (See pubspec.lock):

sentry_dio 6.6.1
sentry_flutter 6.6.1

---

Android 6.0.1

```dart
Fatal Exception: java.lang.NoClassDefFoundError: o.f.s4.b
       at io.sentry.flutter.SentryFlutterPlugin.addBreadcrumb(SentryFlutterPlugin.java:314)
       at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.java:59)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```

**Comment by marandaneto** [comment]
Dupe https://github.com/getsentry/sentry-dart/issues/916
