### ISSUE TITLE
[error] Platform.executable couldn't be retrieved

### ISSUE THREAD

**Issue by davidpanic** [getsentry/sentry-dart#953]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Artix Linux 5.18.12-artix1-1, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /home/david/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • KB2003 (mobile) • cf476e43 • android-arm64  • Android 12 (API 31)
    • Linux (desktop) • linux    • linux-x64      • Artix Linux 5.18.12-artix1-1
    • Chrome (web)    • chrome   • web-javascript • Chromium 103.0.5060.114 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The version of the SDK (See pubspec.lock):
```
sdks:
  dart: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.0"
```

---
I have the following issue:

```
[sentry] [error] Platform.executable couldn't be retrieved.
[sentry] _TypeError (type 'Null' is not a subtype of type 'String')
[sentry] #0      _Platform.executable (dart:io/platform_impl.dart:36:30)
#1      _Platform.executable (dart:io/platform_impl.dart)
#2      Platform.executable (dart:io/platform.dart:179:45)
#3      IoEnricherEventProcessor._getDartContext
package:sentry/…/enricher/io_enricher_event_processor.dart:81
#4      IoEnricherEventProcessor.apply
package:sentry/…/enricher/io_enricher_event_processor.dart:47
#5      SentryClient._processEvent
package:sentry/src/sentry_client.dart:345
           <asynchronous suspension>
#6      SentryClient.captureEvent
package:sentry/src/sentry_client.dart:85
           <asynchronous suspension>
#7      Hub.captureEvent
package:sentry/src/hub.dart:91
           <asynchronous suspension>
#8      FlutterErrorIntegration.call.<anonymous closure>
package:sentry_flutter/src/default_integrations.dart:103
           <asynchronous suspension>
```

**Steps to reproduce:**
```dart
Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = 'https://[REDACTED]'
        ..environment = (kDebugMode ? 'debug' : 'release') + (kProfileMode ? '_profile' : '')
        ..debug = kDebugMode
        ..enableAppLifecycleBreadcrumbs = true
        ..enableAutoNativeBreadcrumbs = true
        ..enableAutoPerformanceTracking = true
        ..enableAutoSessionTracking = true
        ..enableOutOfMemoryTracking = true
        ..reportPackages = true
        ..sendClientReports = true
        ..sendDefaultPii = true
        ..beforeSend = (event, {hint}) {
          final t = event.throwable;
          final ts = t.toString();

          if (t is NoNetworkException) return null;
          if (ts.contains("Failed host lookup: ")) return null;

          return event;
        };
    },
    appRunner: () async {
      WidgetsFlutterBinding.ensureInitialized();
      await Firebase.initializeApp();

      runApp(
        DefaultAssetBundle(
          bundle: SentryAssetBundle(),
          child: App(),
        ),
      );
    },
  );
}
```

**Actual result:**
- Observed exception
- App runs fine, but the exception is printed to the console

**Expected result:**
- Expected the app to without exceptions

**Comment by marandaneto** [comment]
That's normal and not a Sentry's SDK issue https://github.com/getsentry/sentry-dart/blob/4ec11a97eba5207c93cb1dc14103770a0dc2e3f7/dart/lib/src/enricher/io_enricher_event_processor.dart#L79-L88

**Comment by davidpanic** [comment]
Huh?? How is it normal considering it should no longer be returning Null as [this](https://github.com/flutter/engine/pull/33127) was merged on May 5th?

**Comment by ueman** [comment]
It's not yet available on the Flutter stable channel.
